export enum EPermission{
  AUTHORITY_PERMISSION_MANAGEMENT,
  AUTHORITY_USER_MANAGEMENT,
  AUTHORITY_CAMP_MANAGEMENT,
  AUTHORITY_BENEF_MANAGEMENT,
  AUTHORITY_DONATION_MANAGEMENT,
  AUTHORITY_DONATION_APPROVE,
  AUTHORITY_DONATION_REPORTING,
  AUTHORITY_CAMP_REPORTING,
  AUTHORITY_CAMP_IMPORT,
  AUTHORITY_CAMP_REPORTING_RESTRICTED
}
