export enum EPermission{
  PERMISSION_MANAGEMENT,
  USER_MANAGEMENT,
  CAMP_MANAGEMENT,
  BENEF_MANAGEMENT,
  DONATION_MANAGEMENT,
  DONATION_APPROVE,
  DONATION_REPORTING,
  CAMP_REPORTING,
  CAMP_IMPORT,
  CAMP_REPORTING_RESTRICTED
}
